language: ruby
rvm:
- 2.5

before_install:
  - gem install bundler -v 1.17.3
  - rm Gemfile.lock
  - bundle _1.17.3_ install
  - cd _site

# install jekyll from gemfile
install: 
   - bundle install
   - rake
   - chmod +x ./scripts/build.sh
   - ./scripts/build.sh

# build site
scripts: true

deploy:
  provider: netlify
  site: https://cv-emmanouil-brifas.netlify.app/

# deploy to netlify
after_success: 
   - chmod +x ./scripts/deploy.sh
   - ./scripts/deploy.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  
notifications:
  email: false
