language: ruby
rvm:
- 2.2.11

#before_install:
 # - gem install bundler -v 2.2.11
 # - rm Gemfile.lock
 # - bundle _2.2.11_ install


# install jekyll from gemfile
install: 
   - bundle update --bundler
   - bundle install
   - rake
   - chmod +x ./scripts/build.sh
   - ./scripts/build.sh

# build site
scripts: true

# deploy to netlify
after_success: 
   - chmod +x ./scripts/deploy.sh
   - ./scripts/deploy.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master2
  
  
